"""empty message

Revision ID: 468f4da92047
Revises: b14b3dd516dd
Create Date: 2017-11-29 14:31:31.120771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468f4da92047'
down_revision = 'b14b3dd516dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_users', sa.Column('f_lastLoginDate', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('t_users', sa.Column('f_registerDate', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_index('ix_t_users_f_userName', table_name='t_users')
    op.create_index(op.f('ix_t_users_f_userName'), 't_users', ['f_userName'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_users_f_userName'), table_name='t_users')
    op.create_index('ix_t_users_f_userName', 't_users', ['f_userName'], unique=True)
    op.drop_column('t_users', 'f_registerDate')
    op.drop_column('t_users', 'f_lastLoginDate')
    # ### end Alembic commands ###
