"""empty message

Revision ID: 5d945184c694
Revises: 468f4da92047
Create Date: 2017-11-29 15:47:53.072334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d945184c694'
down_revision = '468f4da92047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_users', sa.Column('f_delete', sa.Integer(), nullable=False))
    op.drop_index('ix_t_users_f_userName', table_name='t_users')
    op.create_index(op.f('ix_t_users_f_userName'), 't_users', ['f_userName'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_users_f_userName'), table_name='t_users')
    op.create_index('ix_t_users_f_userName', 't_users', ['f_userName'], unique=True)
    op.drop_column('t_users', 'f_delete')
    # ### end Alembic commands ###
